name = "opengl_1"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Nathan Rignall"]
maintainers = ["Nathan Rignall <rignallnathan@gmail.com>"]
maintainers-logins = ["NathanRignall"]

executables = ["opengl_1"]

[[depends-on]]
openglada = "~0.9.0"
openglada_glfw = "~0.9.0"
openglada_text = "~0.9.0"
